version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:  
    commands:
      - java -version
      - gradle build

artifacts:
  type: zip
  files:
    - 'build/libs/*.jar'
