version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - yum update -y
      - yum install tree -y
  build:  
    commands:
      - tree ~/.pyenv -L 2
#       - sudo yum install tree -y
#       - cd ~/.pyenv
#       - tree -L 2
#       - java -version
#       - gradle build -warning-mode all

# artifacts:
#   type: zip
#   files:
#     - 'build/libs/*.jar'
